In [1]:
pwd

'/Users/kunalkhurana/Documents/TASK2'

In [3]:
import pandas as pd

df = pd.read_csv("customer_support_tickets.csv")

print(df.shape)
df.head()

(8469, 17)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Social media,2023-06-01 12:15:36,NaN,NaN
1,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,I'm having an issue with the {product_purchase...,Pending Customer Response,NaN,Critical,Chat,2023-06-01 16:45:38,NaN,NaN
2,3,Christopher Robbins,gonzalestracy@example.com,48,Other,Dell XPS,2020-07-14,Technical issue,Network problem,I'm facing a problem with my {product_purchase...,Closed,Case maybe show recently my computer follow.,Low,Social media,2023-06-01 11:14:38,2023-06-01 18:05:38,3.0
3,4,Christina Dillon,bradleyolson@example.org,27,Female,Microsoft Office,2020-11-13,Billing inquiry,Account access,I'm having an issue with the {product_purchase...,Closed,Try capital clearly never color toward story.,Low,Social media,2023-06-01 07:29:40,2023-06-01 01:57:40,3.0
4,5,Alexander Carroll,bradleymark@example.com,67,Female,Autodesk AutoCAD,2020-02-04,Billing inquiry,Data loss,I'm having an issue with the {product_purchase...,Closed,West decision evidence bit.,Low,Email,2023-06-01 00:12:42,2023-06-01 19:53:42,1.0

In [4]:
print(df.columns.tolist())

['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution', 'Customer Satisfaction Rating']

In [5]:
df = df[['Ticket Description', 'Ticket Type', 'Ticket Priority']]

df.head()

,Ticket Description,Ticket Type,Ticket Priority
0,I'm having an issue with the {product_purchase...,Technical issue,Critical
1,I'm having an issue with the {product_purchase...,Technical issue,Critical
2,I'm facing a problem with my {product_purchase...,Technical issue,Low
3,I'm having an issue with the {product_purchase...,Billing inquiry,Low
4,I'm having an issue with the {product_purchase...,Billing inquiry,Low

In [6]:
print(df.isnull().sum())

Ticket Description    0
Ticket Type           0
Ticket Priority       0
dtype: int64

In [7]:
import re

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z ]', ' ', text)
    return text

df["clean_text"] = df["Ticket Description"].apply(clean_text)

df[["Ticket Description", "clean_text"]].head()

,Ticket Description,clean_text
0,I'm having an issue with the {product_purchase...,i m having an issue with the product purchase...
1,I'm having an issue with the {product_purchase...,i m having an issue with the product purchase...
2,I'm facing a problem with my {product_purchase...,i m facing a problem with my product purchase...
3,I'm having an issue with the {product_purchase...,i m having an issue with the product purchase...
4,I'm having an issue with the {product_purchase...,i m having an issue with the product purchase...

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words='english'
)

X = vectorizer.fit_transform(df["clean_text"])

print(X.shape)

(8469, 5000)

In [9]:
from sklearn.model_selection import train_test_split

y = df["Ticket Type"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(6775, 5000)
(1694, 5000)

In [10]:
from sklearn.linear_model import LogisticRegression

type_model = LogisticRegression(max_iter=2000)

type_model.fit(X_train, y_train)

print("Model Trained Successfully!")

Model Trained Successfully!

In [11]:
type_model.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [12]:
from sklearn.metrics import accuracy_score, classification_report

pred = type_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, pred))

Accuracy: 0.19893742621015348

In [13]:
print(df["Ticket Type"].value_counts())

Ticket Type
Refund request          1752
Technical issue         1747
Cancellation request    1695
Product inquiry         1641
Billing inquiry         1634
Name: count, dtype: int64

In [14]:
print(df["Ticket Type"].nunique())

5

In [16]:
print(y_train.unique())
print(y_test.unique())

<StringArray>
['Cancellation request',      'Billing inquiry',      'Product inquiry',
       'Refund request',      'Technical issue']
Length: 5, dtype: str
<StringArray>
[      'Refund request',      'Product inquiry',      'Billing inquiry',
 'Cancellation request',      'Technical issue']
Length: 5, dtype: str

In [17]:
print(type_model.classes_)

['Billing inquiry' 'Cancellation request' 'Product inquiry'
 'Refund request' 'Technical issue']

In [18]:
print(pred[:20])

['Refund request' 'Product inquiry' 'Refund request'
 'Cancellation request' 'Billing inquiry' 'Refund request'
 'Refund request' 'Technical issue' 'Product inquiry'
 'Cancellation request' 'Billing inquiry' 'Refund request'
 'Technical issue' 'Product inquiry' 'Product inquiry'
 'Cancellation request' 'Product inquiry' 'Refund request'
 'Refund request' 'Technical issue']

In [19]:
print(y_test.iloc[:20].values)

<StringArray>
[      'Refund request',      'Product inquiry',      'Billing inquiry',
      'Billing inquiry',       'Refund request',       'Refund request',
      'Product inquiry',       'Refund request',       'Refund request',
      'Product inquiry',      'Product inquiry', 'Cancellation request',
      'Technical issue',      'Billing inquiry',      'Technical issue',
 'Cancellation request',      'Product inquiry',      'Billing inquiry',
       'Refund request',      'Billing inquiry']
Length: 20, dtype: str

In [20]:
from collections import Counter

print(Counter(pred))

Counter({'Refund request': 411, 'Technical issue': 385, 'Cancellation request': 337, 'Product inquiry': 301, 'Billing inquiry': 260})

In [21]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

                      precision    recall  f1-score   support

     Billing inquiry       0.17      0.12      0.14       357
Cancellation request       0.18      0.19      0.18       327
     Product inquiry       0.20      0.19      0.19       316
      Refund request       0.20      0.24      0.22       345
     Technical issue       0.23      0.26      0.24       349

            accuracy                           0.20      1694
           macro avg       0.20      0.20      0.20      1694
        weighted avg       0.20      0.20      0.20      1694

In [22]:
print(type(y_test))
print(type(pred))

<class 'pandas.Series'>
<class 'numpy.ndarray'>

In [23]:
y = df["Ticket Type"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.linear_model import LogisticRegression

type_model = LogisticRegression(max_iter=2000)

type_model.fit(X_train, y_train)

pred = type_model.predict(X_test)

from sklearn.metrics import accuracy_score

print("Accuracy =", accuracy_score(y_test, pred))

Accuracy = 0.20425029515938606

In [25]:
print(df.columns.tolist())

['Ticket Description', 'Ticket Type', 'Ticket Priority', 'clean_text']

In [26]:
import pandas as pd

df = pd.read_csv("customer_support_tickets.csv")

In [27]:
print(df.columns.tolist())

['Ticket ID', 'Customer Name', 'Customer Email', 'Customer Age', 'Customer Gender', 'Product Purchased', 'Date of Purchase', 'Ticket Type', 'Ticket Subject', 'Ticket Description', 'Ticket Status', 'Resolution', 'Ticket Priority', 'Ticket Channel', 'First Response Time', 'Time to Resolution', 'Customer Satisfaction Rating']

In [28]:
df["text"] = (
    df["Ticket Subject"].astype(str)
    + " "
    + df["Ticket Description"].astype(str)
)

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words="english"
)

X = vectorizer.fit_transform(df["text"])

print(X.shape)

(8469, 5000)

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

y = df["Ticket Type"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

type_model = LogisticRegression(max_iter=2000)

type_model.fit(X_train, y_train)

pred = type_model.predict(X_test)

print("Accuracy =", accuracy_score(y_test, pred))

Accuracy = 0.2077922077922078

In [32]:
import os

print(os.getcwd())
print(os.listdir())

/Users/kunalkhurana/Documents/TASK2
['customer_support_tickets.csv', '.DS_Store', 'Untitled.ipynb', '.ipynb_checkpoints', 'all_tickets_processed_improved_v3.csv']

In [33]:
import pandas as pd

df = pd.read_csv("all_tickets_processed_improved_v3.csv")

print(df.shape)
print(df.columns.tolist())

df.head()

(47838, 1)
['all_tickets_processed_improved_v3']

                                                   all_tickets_processed_improved_v3
Document                                                                 Topic_group
connection with icon icon dear please setup ico...                          Hardware
work experience user work experience user hi wo...                            Access
requesting for meeting requesting meeting hi pl...                          Hardware
reset passwords for external accounts re expire...                            Access

In [34]:
print(df.columns)

Index(['all_tickets_processed_improved_v3'], dtype='str')

In [35]:
print(df.shape)
print(df.columns.tolist())

(47838, 1)
['all_tickets_processed_improved_v3']

In [36]:
df.head()

                                                   all_tickets_processed_improved_v3
Document                                                                 Topic_group
connection with icon icon dear please setup ico...                          Hardware
work experience user work experience user hi wo...                            Access
requesting for meeting requesting meeting hi pl...                          Hardware
reset passwords for external accounts re expire...                            Access

In [38]:
for col in df.columns:
    print(repr(col))

'all_tickets_processed_improved_v3'

In [39]:
print(df.head())

                                                   all_tickets_processed_improved_v3
Document                                                                 Topic_group
connection with icon icon dear please setup ico...                          Hardware
work experience user work experience user hi wo...                            Access
requesting for meeting requesting meeting hi pl...                          Hardware
reset passwords for external accounts re expire...                            Access

In [40]:
print(df.shape)

(47838, 1)

In [41]:
df = pd.read_csv(
    "all_tickets_processed_improved_v3.csv",
    sep="|"
)

print(df.shape)
print(df.columns)

(47838, 1)
Index(['all_tickets_processed_improved_v3'], dtype='str')

In [42]:
with open("all_tickets_processed_improved_v3.csv", "r", encoding="utf-8", errors="ignore") as f:
    for i in range(10):
        print(repr(f.readline()))

'all_tickets_processed_improved_v3\n'
'Document,Topic_group\n'
'connection with icon icon dear please setup icon per icon engineers please let other details needed thanks lead,Hardware\n'
'work experience user work experience user hi work experience student coming next his name much appreciate him duration thank,Access\n'
'requesting for meeting requesting meeting hi please help follow equipments cable pc cord plug,Hardware\n'
'reset passwords for external accounts re expire days hi ask help update passwords colleagues thank pm expire days importance high hi received about expiration please kindly help prolongation best regards pm expire days importance high dear expire days order change please follow steps prerequisites disable device credentials close active connected by cable machine note also follow steps detailed press ctrl alt delete same pops change item enter format enter enter newly chosen then re enter again submit displaying has changed os machine browse enter format enter gear icon top tight browser window enter enter newly chosen then re enter again save connected note complete resources granted once connected by cable browse tick want change after logging enter format enter log enter enter newly chosen then re enter again change clients suppliers about expire please touch person then communicate back encounter issues hesitate by accessing yours,Access\n'
'mail verification warning hi has got attached please addresses best regards monitoring analyst verification warning,Miscellaneous\n'
'mail please dear looks blacklisted receiving mails anymore sample attached thanks kind regards senior engineer,Miscellaneous\n'
'prod servers tunneling prod tunneling va la tunneling la host si la si host host cards port name bytes bytes seq bytes seq statistics packets transmitted received packet loss avg bytes bytes seq bytes seq tuesday pm acre re tunneling si pm acre re tunneling extended object host extended host extended object host range extended host range administrator re sector pm acre re tunneling va la si la tunneling design lead ext friday pm re tunneling va extended object host extended host administrator re sector pm tunneling va la tunneling users pinging bytes bytes bytes bytes bytes design lead ext con care pot partial strict si pot ale care va la contains proprietary information which legally privileged unauthorized dissemination prohibited intended recipient views addressing transmission error has misdirected please notify author by replying intended recipient must disclose distribute copy print rely,Hardware\n'
'access request dear modules report report cost thank much regards,HR Support\n'

In [43]:
import pandas as pd

df = pd.read_csv(
    "all_tickets_processed_improved_v3.csv",
    skiprows=1
)

print(df.shape)
print(df.columns.tolist())
df.head()

(47837, 2)
['Document', 'Topic_group']

                                            Document    Topic_group
0  connection with icon icon dear please setup ic...       Hardware
1  work experience user work experience user hi w...         Access
2  requesting for meeting requesting meeting hi p...       Hardware
3  reset passwords for external accounts re expir...         Access
4  mail verification warning hi has got attached ...  Miscellaneous

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    max_features=10000,
    stop_words="english"
)

X = vectorizer.fit_transform(df["Document"])

y = df["Topic_group"]

print(X.shape)

(47837, 10000)

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print(X_train.shape)
print(X_test.shape)

(38269, 10000)
(9568, 10000)

In [46]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=3000)

model.fit(X_train, y_train)

print("Training Complete")

Training Complete

In [47]:
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

print("Accuracy =", accuracy_score(y_test, pred))

Accuracy = 0.8481396321070234

In [48]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

                       precision    recall  f1-score   support

               Access       0.91      0.87      0.89      1425
Administrative rights       0.89      0.65      0.75       352
           HR Support       0.86      0.85      0.85      2183
             Hardware       0.78      0.89      0.83      2724
     Internal Project       0.91      0.80      0.85       424
        Miscellaneous       0.82      0.81      0.82      1412
             Purchase       0.98      0.87      0.92       493
              Storage       0.94      0.84      0.89       555

             accuracy                           0.85      9568
            macro avg       0.89      0.82      0.85      9568
         weighted avg       0.85      0.85      0.85      9568

In [49]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, pred)

print(cm)

[[1235    4   39   95    3   44    1    4]
 [   7  228    9   97    0   10    1    0]
 [  31    2 1852  209   10   73    0    6]
 [  52   15  127 2416   10   91    5    8]
 [   2    0   33   33  339   17    0    0]
 [  20    1   75  146    9 1150    2    9]
 [   2    3    7   42    1    9  428    1]
 [   1    2   24   51    0   10    0  467]]

In [50]:
import joblib

joblib.dump(model, "ticket_classifier.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

print("Model Saved")

Model Saved

In [51]:
new_ticket = ["unable to login account password reset required"]

x_new = vectorizer.transform(new_ticket)

prediction = model.predict(x_new)

print(prediction[0])

Access

In [52]:
test_tickets = [
    "printer not working and cable issue",
    "need software installation",
    "password reset required urgently",
    "email verification warning received",
    "laptop hardware issue"
]

x = vectorizer.transform(test_tickets)

predictions = model.predict(x)

for ticket, pred in zip(test_tickets, predictions):
    print(ticket, " ---> ", pred)

printer not working and cable issue  --->  Hardware
need software installation  --->  Administrative rights
password reset required urgently  --->  Access
email verification warning received  --->  Miscellaneous
laptop hardware issue  --->  Hardware

In [54]:
pred = model.predict(x_new)[0]

In [55]:
pred_test = model.predict(X_test)

from sklearn.metrics import classification_report

print(classification_report(y_test, pred_test))

                       precision    recall  f1-score   support

               Access       0.91      0.87      0.89      1425
Administrative rights       0.89      0.65      0.75       352
           HR Support       0.86      0.85      0.85      2183
             Hardware       0.78      0.89      0.83      2724
     Internal Project       0.91      0.80      0.85       424
        Miscellaneous       0.82      0.81      0.82      1412
             Purchase       0.98      0.87      0.92       493
              Storage       0.94      0.84      0.89       555

             accuracy                           0.85      9568
            macro avg       0.89      0.82      0.85      9568
         weighted avg       0.85      0.85      0.85      9568

In [56]:
import joblib

joblib.dump(model, "ticket_classifier.pkl")
joblib.dump(vectorizer, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

In [57]:
import os

print(os.listdir())

['customer_support_tickets.csv', 'tfidf_vectorizer.pkl', 'Untitled1.ipynb', '.DS_Store', 'Untitled.ipynb', 'ticket_classifier.pkl', '.ipynb_checkpoints', 'all_tickets_processed_improved_v3.csv']